 wget -P ./models/Lora https://civitai.com/api/download/models/63006   --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/112969  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/32988  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/44566  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/103767  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/28907  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/78559  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/16557  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/28609  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/7804  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/102533  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/7657  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/52870  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/8339  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/25661  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/21173  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/150907  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/10350  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/67980  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/9470  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/60568  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/87153  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/16576  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/8527  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/126824  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/118945  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/123732  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/123434  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/42855  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/123309  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/92506  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/121658  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/44995  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/129821  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/146600  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/143150  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/122023  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/55466  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/106626  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/126807  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/79886  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/145907  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/152317  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/134916  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/58887  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/95927  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/114505  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/110963  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/152316  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/124043  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/68210  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/117191  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/73852  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/93704  --content-disposition
 wget -P ./models/Lora https://civitai.com/api/download/models/127755 --content-disposition